
-- username: amm 
-- password: 111

create table utente(
    id_utente integer generated by default as identity primary key,
    nome varchar(32),
    cognome varchar(32),
    dataNascita date,
    frasePresentazione varchar(140),
    password varchar(16) not null,
    urlFotoProfilo varchar(256),
    superUtente boolean not null,
    username varchar(64) not null unique
    
);

create table postType(
    id_postType integer generated by default as identity primary key,
    nome varchar(16) unique
);

create table gruppo(
    id_gruppo integer generated by default as identity primary key,
    nome varchar(256),
    admin integer references utente on delete cascade
);

create table post(
    id_post integer generated by default as identity primary key,
    content varchar(2048),
    urlAllegato varchar(256),
    tipo integer references postType on delete cascade not null,
    autore integer references utente on delete cascade,
    utenteDestinatario integer references utente on delete cascade,
    gruppoDestinatario integer references gruppo on delete cascade,
    check ((utenteDestinatario is null and gruppoDestinatario is not null)
            or (gruppoDestinatario is null and utenteDestinatario is not null))
);

create table amicizia(
    utente integer references utente on delete cascade,
    amico integer references utente on delete cascade,
    primary key (utente, amico)
);

create table appartenenzaGruppo(
    utente integer references utente on delete cascade,
    gruppo integer references gruppo on delete cascade,
    primary key (utente, gruppo)
);



insert into utente(id_utente, username, nome, cognome, dataNascita, frasePresentazione, password, urlFotoProfilo, superUtente)
values 	(default, 'Genoveffo','Genoveffo', 'Rossi', '1990-02-21', 'lalala lalalaaaaaa', '111', 'img/nerd-urkel.jpg', true),
	(default, 'Matteo', 'Matteo', 'Anedda', '1980-10-15', null, '111', 'img/imges.jpg', false),
        (default, 'Marta', 'Marta', 'Usai', '2000-07-07', 'hjkdhskjdsh kjhsdjhds jshkjds', '111', 'img/gatto.jpg', false),
        (default, 'Marco', 'Marco', 'Mura', '1992-06-03', null, '111', 'img/messi.jpg', false),
        (default, 'cancellami', 'Canc', 'Ellami', '1990-02-03', null, '111', 'img/profilo.jpg', false);

insert into postType(id_postType, nome)
values 	(default, 'text'), 
	(default, 'image'), 
	(default, 'link'); 
		
insert into gruppo(id_gruppo, nome, admin)
values 	(default, 'Nerd', 1),
	(default, 'Calcetto', 4),
        (default, 'Eliminare', 5);
		
insert into post(id_post, autore, utenteDestinatario, gruppoDestinatario, tipo, content, urlAllegato)
values	(default, 1, 1, null, 1, 'Oggi è proprio una bella giornata', ''),
        (default, 1, 2, null, 2, '', 'img/imgPost2.jpg'),
        (default, 2, 1, null, 2, 'Ahahahaaaaaa', 'img/imgPost3.jpeg'),
        (default, 3, 3, null, 2, '', 'img/imagesPost.jpg'),
        (default, 2, 2, null, 1, 'Ciao e buona giornata a tutti amici', ''),
        (default, 4, 4, null, 3, 'Vamos blaugrana !!!', 'http://it.wikipedia.org/wiki/Futbol_Club_Barcelona'),
        (default, 1, null, 2, 1, 'Chi gioca oggi?', ''),
        (default, 5, null, 3, 1, 'blablablablabla ','');
		
insert into amicizia(utente, amico)
values 	(1, 2),
        (1, 3),
        (1, 4),
        (2, 1),
        (2, 4),
        (3, 1),
        (3, 4),
        (4, 1),
        (4, 2),
        (4, 3),
        (5, 1),
        (1, 5);
       
		
insert into appartenenzaGruppo( utente, gruppo)
values 	(1, 1),
        (2, 1),
        (3, 1),
        (4, 1),
        (1, 2),
        (3, 2),
        (4, 2),
        (5, 3),
        (1, 3);
		
